#!/bin/sh

# Pre-installation shell script for Debian package

SYSTEMD=/etc/systemd/system/multi-user.target.wants
SERVICE=nginx.service

sudo rm -fr /etc/nginx/sites-enabled/default
sudo mkdir -p /var/www/html/portal

# Stop and disable Nginx service
if [ -f $SYSTEMD/$SERVICE ]; then
  systemctl is-active $SERVICE > /dev/null 2>&1 && sudo systemctl stop $SERVICE
  sudo systemctl disable $SERVICE
fi
